import "./globals.css";
import "@repo/ui/styles";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
// import ModeToggleButton from "@/components/ModeToggleButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turbo App",
  description: "Generated by create turbo app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script src="https://cdn.tailwindcss.com"></script>
      <body className={inter.className}>
        <ThemeProvider attribute="class" enableSystem>
          {/* <ModeToggleButton /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
